/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActionResultResponse } from '../model/models';
import { ExecuteActionRequest } from '../model/models';
import { SavedItemListResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ExecuteActionRequestParams {
    executeActionRequest: ExecuteActionRequest;
    xTenantID?: string;
}

export interface ListSavedItemsRequestParams {
    sessionId: string;
    xTenantID?: string;
}

export interface RemoveSavedItemRequestParams {
    itemId: string;
    sessionId: string;
    xTenantID?: string;
}


export interface ActionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Execute an action
     * 
     * @endpoint post /api/v1/actions/execute
* @param requestParameters
     */
    executeAction(requestParameters: ExecuteActionRequestParams, extraHttpRequestParams?: any): Observable<ActionResultResponse>;

    /**
     * List saved items
     * 
     * @endpoint get /api/v1/actions/saved-items
* @param requestParameters
     */
    listSavedItems(requestParameters: ListSavedItemsRequestParams, extraHttpRequestParams?: any): Observable<SavedItemListResponse>;

    /**
     * Remove a saved item
     * 
     * @endpoint delete /api/v1/actions/saved-items/{itemId}
* @param requestParameters
     */
    removeSavedItem(requestParameters: RemoveSavedItemRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
