/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AnalyticsSummaryResponse } from '../model/models';
import { BillingResponse } from '../model/models';
import { PlatformRollupResponse } from '../model/models';
import { ProblemDetails } from '../model/models';
import { TokenUsageResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetAnalyticsSummaryRequestParams {
    xTenantID?: string;
    from?: string;
    to?: string;
}

export interface GetBillingRequestParams {
    xTenantID?: string;
    from?: string;
    to?: string;
}

export interface GetPlatformRollupRequestParams {
    from?: string;
    to?: string;
}

export interface GetTokenUsageRequestParams {
    xTenantID?: string;
    from?: string;
    to?: string;
}


export interface AnalyticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get analytics summary
     * 
     * @endpoint get /api/v1/analytics/summary
* @param requestParameters
     */
    getAnalyticsSummary(requestParameters: GetAnalyticsSummaryRequestParams, extraHttpRequestParams?: any): Observable<AnalyticsSummaryResponse>;

    /**
     * Get billing info
     * 
     * @endpoint get /api/v1/analytics/billing
* @param requestParameters
     */
    getBilling(requestParameters: GetBillingRequestParams, extraHttpRequestParams?: any): Observable<BillingResponse>;

    /**
     * Get platform-wide rollup
     * 
     * @endpoint get /api/v1/analytics/platform
* @param requestParameters
     */
    getPlatformRollup(requestParameters: GetPlatformRollupRequestParams, extraHttpRequestParams?: any): Observable<PlatformRollupResponse>;

    /**
     * Get token usage
     * 
     * @endpoint get /api/v1/analytics/tokens
* @param requestParameters
     */
    getTokenUsage(requestParameters: GetTokenUsageRequestParams, extraHttpRequestParams?: any): Observable<TokenUsageResponse>;

}
