/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplicationResponse } from '../model/models';
import { CreateApplicationRequest } from '../model/models';
import { ListApplications200Response } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateApplicationRequestParams {
    createApplicationRequest: CreateApplicationRequest;
    xTenantID?: string;
}

export interface DeleteApplicationRequestParams {
    appId: string;
    xTenantID?: string;
}

export interface GetApplicationRequestParams {
    appId: string;
    xTenantID?: string;
}

export interface ListApplicationsRequestParams {
    xTenantID?: string;
}


export interface ApplicationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new application
     * 
     * @endpoint post /api/v1/applications
* @param requestParameters
     */
    createApplication(requestParameters: CreateApplicationRequestParams, extraHttpRequestParams?: any): Observable<ApplicationResponse>;

    /**
     * Delete an application
     * 
     * @endpoint delete /api/v1/applications/{appId}
* @param requestParameters
     */
    deleteApplication(requestParameters: DeleteApplicationRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get application by ID
     * 
     * @endpoint get /api/v1/applications/{appId}
* @param requestParameters
     */
    getApplication(requestParameters: GetApplicationRequestParams, extraHttpRequestParams?: any): Observable<ApplicationResponse>;

    /**
     * List applications for a tenant
     * 
     * @endpoint get /api/v1/applications
* @param requestParameters
     */
    listApplications(requestParameters: ListApplicationsRequestParams, extraHttpRequestParams?: any): Observable<ListApplications200Response>;

}
