/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActionsConfigResponse } from '../model/models';
import { AiPersonaResponse } from '../model/models';
import { ComponentsToggleResponse } from '../model/models';
import { GuardrailsResponse } from '../model/models';
import { LlmProviderResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetActionsConfigRequestParams {
    xTenantID?: string;
}

export interface GetAiConfigRequestParams {
    xTenantID?: string;
}

export interface GetComponentsConfigRequestParams {
    xTenantID?: string;
}

export interface GetGuardrailsConfigRequestParams {
    xTenantID?: string;
}

export interface GetLlmConfigRequestParams {
    xTenantID?: string;
}

export interface UpdateActionsConfigRequestParams {
    actionsConfigResponse: ActionsConfigResponse;
    xTenantID?: string;
}

export interface UpdateAiConfigRequestParams {
    aiPersonaResponse: AiPersonaResponse;
    xTenantID?: string;
}

export interface UpdateComponentsConfigRequestParams {
    componentsToggleResponse: ComponentsToggleResponse;
    xTenantID?: string;
}

export interface UpdateGuardrailsConfigRequestParams {
    guardrailsResponse: GuardrailsResponse;
    xTenantID?: string;
}

export interface UpdateLlmConfigRequestParams {
    llmProviderResponse: LlmProviderResponse;
    xTenantID?: string;
}


export interface ConfigServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get actions config
     * 
     * @endpoint get /api/v1/config/actions
* @param requestParameters
     */
    getActionsConfig(requestParameters: GetActionsConfigRequestParams, extraHttpRequestParams?: any): Observable<ActionsConfigResponse>;

    /**
     * Get ai config
     * 
     * @endpoint get /api/v1/config/ai
* @param requestParameters
     */
    getAiConfig(requestParameters: GetAiConfigRequestParams, extraHttpRequestParams?: any): Observable<AiPersonaResponse>;

    /**
     * Get components config
     * 
     * @endpoint get /api/v1/config/components
* @param requestParameters
     */
    getComponentsConfig(requestParameters: GetComponentsConfigRequestParams, extraHttpRequestParams?: any): Observable<ComponentsToggleResponse>;

    /**
     * Get guardrails config
     * 
     * @endpoint get /api/v1/config/guardrails
* @param requestParameters
     */
    getGuardrailsConfig(requestParameters: GetGuardrailsConfigRequestParams, extraHttpRequestParams?: any): Observable<GuardrailsResponse>;

    /**
     * Get llm config
     * 
     * @endpoint get /api/v1/config/llm
* @param requestParameters
     */
    getLlmConfig(requestParameters: GetLlmConfigRequestParams, extraHttpRequestParams?: any): Observable<LlmProviderResponse>;

    /**
     * Update actions config
     * 
     * @endpoint patch /api/v1/config/actions
* @param requestParameters
     */
    updateActionsConfig(requestParameters: UpdateActionsConfigRequestParams, extraHttpRequestParams?: any): Observable<ActionsConfigResponse>;

    /**
     * Update ai config
     * 
     * @endpoint patch /api/v1/config/ai
* @param requestParameters
     */
    updateAiConfig(requestParameters: UpdateAiConfigRequestParams, extraHttpRequestParams?: any): Observable<AiPersonaResponse>;

    /**
     * Update components config
     * 
     * @endpoint patch /api/v1/config/components
* @param requestParameters
     */
    updateComponentsConfig(requestParameters: UpdateComponentsConfigRequestParams, extraHttpRequestParams?: any): Observable<ComponentsToggleResponse>;

    /**
     * Update guardrails config
     * 
     * @endpoint patch /api/v1/config/guardrails
* @param requestParameters
     */
    updateGuardrailsConfig(requestParameters: UpdateGuardrailsConfigRequestParams, extraHttpRequestParams?: any): Observable<GuardrailsResponse>;

    /**
     * Update llm config
     * 
     * @endpoint patch /api/v1/config/llm
* @param requestParameters
     */
    updateLlmConfig(requestParameters: UpdateLlmConfigRequestParams, extraHttpRequestParams?: any): Observable<LlmProviderResponse>;

}
