/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateDataSourceRequest } from '../model/models';
import { DataSourceResponse } from '../model/models';
import { ListDataSources200Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateDataSourceRequestParams {
    createDataSourceRequest: CreateDataSourceRequest;
    xTenantID?: string;
}

export interface DeleteDataSourceRequestParams {
    dataSourceId: string;
    xTenantID?: string;
}

export interface GetDataSourceRequestParams {
    dataSourceId: string;
    xTenantID?: string;
}

export interface ListDataSourcesRequestParams {
    xTenantID?: string;
}


export interface DataSourcesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new data source
     * 
     * @endpoint post /api/v1/datasources
* @param requestParameters
     */
    createDataSource(requestParameters: CreateDataSourceRequestParams, extraHttpRequestParams?: any): Observable<DataSourceResponse>;

    /**
     * Delete a data source
     * 
     * @endpoint delete /api/v1/datasources/{dataSourceId}
* @param requestParameters
     */
    deleteDataSource(requestParameters: DeleteDataSourceRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get data source by ID
     * 
     * @endpoint get /api/v1/datasources/{dataSourceId}
* @param requestParameters
     */
    getDataSource(requestParameters: GetDataSourceRequestParams, extraHttpRequestParams?: any): Observable<DataSourceResponse>;

    /**
     * List data sources for a tenant
     * 
     * @endpoint get /api/v1/datasources
* @param requestParameters
     */
    listDataSources(requestParameters: ListDataSourcesRequestParams, extraHttpRequestParams?: any): Observable<ListDataSources200Response>;

}
