/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HealthResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Liveness probe
     * 
     * @endpoint get /api/v1/health
*/
    healthCheck(extraHttpRequestParams?: any): Observable<HealthResponse>;

    /**
     * Readiness probe
     * 
     * @endpoint get /api/v1/health/ready
*/
    readinessCheck(extraHttpRequestParams?: any): Observable<HealthResponse>;

}
