/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { NotificationCountResponse } from '../model/models';
import { NotificationListResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ClearAllNotificationsRequestParams {
    xTenantID?: string;
}

export interface DismissNotificationRequestParams {
    id: string;
}

export interface GetUnreadNotificationCountRequestParams {
    xTenantID?: string;
}

export interface ListNotificationsRequestParams {
    xTenantID?: string;
    unreadOnly?: boolean;
    before?: string;
    limit?: number;
}

export interface MarkAllNotificationsReadRequestParams {
    xTenantID?: string;
}

export interface MarkNotificationAsReadRequestParams {
    id: string;
}


export interface NotificationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Clear all notifications
     * Deletes all notifications for the authenticated user in the specified tenant. 
     * @endpoint delete /api/v1/notifications
* @param requestParameters
     */
    clearAllNotifications(requestParameters: ClearAllNotificationsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Dismiss a notification
     * Permanently deletes a single notification for the authenticated user.
     * @endpoint delete /api/v1/notifications/{id}
* @param requestParameters
     */
    dismissNotification(requestParameters: DismissNotificationRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get unread notification count
     * Returns the number of unread notifications for the bell badge.
     * @endpoint get /api/v1/notifications/unread-count
* @param requestParameters
     */
    getUnreadNotificationCount(requestParameters: GetUnreadNotificationCountRequestParams, extraHttpRequestParams?: any): Observable<NotificationCountResponse>;

    /**
     * List notifications
     * Cursor-based notification list for the authenticated user. Returns notifications for the specified tenant, ordered by creation time descending. 
     * @endpoint get /api/v1/notifications
* @param requestParameters
     */
    listNotifications(requestParameters: ListNotificationsRequestParams, extraHttpRequestParams?: any): Observable<NotificationListResponse>;

    /**
     * Mark all notifications as read
     * Marks all unread notifications as read for the authenticated user in the specified tenant. 
     * @endpoint post /api/v1/notifications/read-all
* @param requestParameters
     */
    markAllNotificationsRead(requestParameters: MarkAllNotificationsReadRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Mark a notification as read
     * Marks a single notification as read for the authenticated user.
     * @endpoint patch /api/v1/notifications/{id}
* @param requestParameters
     */
    markNotificationAsRead(requestParameters: MarkNotificationAsReadRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
