/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CollectionListResponse } from '../model/models';
import { ProblemDetails } from '../model/models';
import { QueryResultResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface InferSchemaRequestParams {
    collection: string;
    xTenantID?: string;
}

export interface ListCollectionsRequestParams {
    xTenantID?: string;
}

export interface QueryCollectionRequestParams {
    collection: string;
    xTenantID?: string;
    limit?: number;
    requestBody?: { [key: string]: any; };
}


export interface SchemaRegistryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Infer collection schema
     * 
     * @endpoint get /api/v1/schema-registry/infer/{collection}
* @param requestParameters
     */
    inferSchema(requestParameters: InferSchemaRequestParams, extraHttpRequestParams?: any): Observable<{ [key: string]: string; }>;

    /**
     * List MongoDB collections
     * 
     * @endpoint get /api/v1/schema-registry/collections
* @param requestParameters
     */
    listCollections(requestParameters: ListCollectionsRequestParams, extraHttpRequestParams?: any): Observable<CollectionListResponse>;

    /**
     * Query a collection
     * 
     * @endpoint post /api/v1/schema-registry/query/{collection}
* @param requestParameters
     */
    queryCollection(requestParameters: QueryCollectionRequestParams, extraHttpRequestParams?: any): Observable<QueryResultResponse>;

}
