/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTenantRequest } from '../model/models';
import { InviteAdminRequest } from '../model/models';
import { TenantAdminResponse } from '../model/models';
import { TenantResponse } from '../model/models';
import { UpdateTenantRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateTenantRequestParams {
    createTenantRequest: CreateTenantRequest;
}

export interface GetTenantRequestParams {
    tenantId: string;
}

export interface InviteAdminRequestParams {
    tenantId: string;
    inviteAdminRequest: InviteAdminRequest;
}

export interface ListTenantAdminsRequestParams {
    tenantId: string;
}

export interface UpdateTenantRequestParams {
    tenantId: string;
    updateTenantRequest: UpdateTenantRequest;
}


export interface TenantsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new tenant
     * 
     * @endpoint post /api/v1/tenants
* @param requestParameters
     */
    createTenant(requestParameters: CreateTenantRequestParams, extraHttpRequestParams?: any): Observable<TenantResponse>;

    /**
     * Get tenant by ID
     * 
     * @endpoint get /api/v1/tenants/{tenantId}
* @param requestParameters
     */
    getTenant(requestParameters: GetTenantRequestParams, extraHttpRequestParams?: any): Observable<TenantResponse>;

    /**
     * Invite a tenant admin
     * 
     * @endpoint post /api/v1/tenants/{tenantId}/admins
* @param requestParameters
     */
    inviteAdmin(requestParameters: InviteAdminRequestParams, extraHttpRequestParams?: any): Observable<TenantAdminResponse>;

    /**
     * List tenant admins
     * 
     * @endpoint get /api/v1/tenants/{tenantId}/admins
* @param requestParameters
     */
    listTenantAdmins(requestParameters: ListTenantAdminsRequestParams, extraHttpRequestParams?: any): Observable<Array<TenantAdminResponse>>;

    /**
     * Update tenant
     * 
     * @endpoint patch /api/v1/tenants/{tenantId}
* @param requestParameters
     */
    updateTenant(requestParameters: UpdateTenantRequestParams, extraHttpRequestParams?: any): Observable<TenantResponse>;

}
