/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.synaptiq.infrastructure.in.web.api;

import com.synaptiq.infrastructure.in.web.dto.ApplicationResponse;
import com.synaptiq.infrastructure.in.web.dto.CreateApplicationRequest;
import com.synaptiq.infrastructure.in.web.dto.ListApplications200Response;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-05T21:15:25.464614100-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Applications", description = "Application lifecycle — create, read, delete application configurations")
public interface ApplicationsApi {

    String PATH_CREATE_APPLICATION = "/api/v1/applications";
    /**
     * POST /api/v1/applications : Create a new application
     *
     * @param createApplicationRequest  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Application created (status code 201)
     */
    @Operation(
        operationId = "createApplication",
        summary = "Create a new application",
        tags = { "Applications" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Application created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApplicationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApplicationsApi.PATH_CREATE_APPLICATION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<ApplicationResponse>> createApplication(
        @Parameter(name = "CreateApplicationRequest", description = "", required = true) @Valid @RequestBody Mono<CreateApplicationRequest> createApplicationRequest,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_DELETE_APPLICATION = "/api/v1/applications/{appId}";
    /**
     * DELETE /api/v1/applications/{appId} : Delete an application
     *
     * @param appId  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Application deleted (status code 204)
     */
    @Operation(
        operationId = "deleteApplication",
        summary = "Delete an application",
        tags = { "Applications" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Application deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ApplicationsApi.PATH_DELETE_APPLICATION
    )
    Mono<ResponseEntity<Void>> deleteApplication(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_APPLICATION = "/api/v1/applications/{appId}";
    /**
     * GET /api/v1/applications/{appId} : Get application by ID
     *
     * @param appId  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Application details (status code 200)
     */
    @Operation(
        operationId = "getApplication",
        summary = "Get application by ID",
        tags = { "Applications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Application details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApplicationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApplicationsApi.PATH_GET_APPLICATION,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<ApplicationResponse>> getApplication(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_APPLICATIONS = "/api/v1/applications";
    /**
     * GET /api/v1/applications : List applications for a tenant
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Application list (status code 200)
     */
    @Operation(
        operationId = "listApplications",
        summary = "List applications for a tenant",
        tags = { "Applications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Application list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListApplications200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApplicationsApi.PATH_LIST_APPLICATIONS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<ListApplications200Response>> listApplications(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
