/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.synaptiq.infrastructure.in.web.api;

import com.synaptiq.infrastructure.in.web.dto.AuthTokenResponse;
import com.synaptiq.infrastructure.in.web.dto.ChangePasswordRequest;
import com.synaptiq.infrastructure.in.web.dto.LoginRequest;
import com.synaptiq.infrastructure.in.web.dto.ProblemDetails;
import com.synaptiq.infrastructure.in.web.dto.SignupRequest;
import com.synaptiq.infrastructure.in.web.dto.UpdateRoleRequest;
import com.synaptiq.infrastructure.in.web.dto.UserResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-08T22:14:16.718368-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Auth", description = "Authentication — signup, login, token management")
public interface AuthApi {

    String PATH_CHANGE_PASSWORD = "/api/v1/auth/change-password";
    /**
     * POST /api/v1/auth/change-password : Change password
     *
     * @param changePasswordRequest  (required)
     * @return Password changed (status code 204)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "changePassword",
        summary = "Change password",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Password changed"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_CHANGE_PASSWORD,
        produces = { "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<Void>> changePassword(
        @Parameter(name = "ChangePasswordRequest", description = "", required = true) @Valid @RequestBody Mono<ChangePasswordRequest> changePasswordRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_CURRENT_USER = "/api/v1/auth/me";
    /**
     * GET /api/v1/auth/me : Get current user profile
     *
     * @return Current user (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getCurrentUser",
        summary = "Get current user profile",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Current user", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = UserResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuthApi.PATH_GET_CURRENT_USER,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<UserResponse>> getCurrentUser(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LOGIN = "/api/v1/auth/login";
    /**
     * POST /api/v1/auth/login : Authenticate user
     *
     * @param loginRequest  (required)
     * @return Authentication successful (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "login",
        summary = "Authenticate user",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Authentication successful", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthTokenResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = AuthTokenResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_LOGIN,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<AuthTokenResponse>> login(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody Mono<LoginRequest> loginRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_REFRESH_TOKEN = "/api/v1/auth/refresh";
    /**
     * POST /api/v1/auth/refresh : Refresh access token
     *
     * @return Token refreshed (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "refreshToken",
        summary = "Refresh access token",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Token refreshed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthTokenResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = AuthTokenResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_REFRESH_TOKEN,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<AuthTokenResponse>> refreshToken(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_SIGNUP = "/api/v1/auth/signup";
    /**
     * POST /api/v1/auth/signup : Register a new user
     *
     * @param signupRequest  (required)
     * @return User created (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "signup",
        summary = "Register a new user",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "201", description = "User created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = UserResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_SIGNUP,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<UserResponse>> signup(
        @Parameter(name = "SignupRequest", description = "", required = true) @Valid @RequestBody Mono<SignupRequest> signupRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPDATE_USER_ROLE = "/api/v1/auth/me/role";
    /**
     * PATCH /api/v1/auth/me/role : Update current user role
     *
     * @param updateRoleRequest  (required)
     * @return Role updated (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateUserRole",
        summary = "Update current user role",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Role updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = UserResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = AuthApi.PATH_UPDATE_USER_ROLE,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<UserResponse>> updateUserRole(
        @Parameter(name = "UpdateRoleRequest", description = "", required = true) @Valid @RequestBody Mono<UpdateRoleRequest> updateRoleRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
