/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.synaptiq.infrastructure.in.web.api;

import com.synaptiq.infrastructure.in.web.dto.ChatMessageRequest;
import com.synaptiq.infrastructure.in.web.dto.CreateSessionRequest;
import org.springframework.lang.Nullable;
import com.synaptiq.infrastructure.in.web.dto.SessionHistoryResponse;
import com.synaptiq.infrastructure.in.web.dto.SessionListResponse;
import com.synaptiq.infrastructure.in.web.dto.SessionResponse;
import com.synaptiq.infrastructure.in.web.dto.UpdateSessionRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-05T21:15:25.464614100-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Chat", description = "Conversational AI — sessions, messages, context management")
public interface ChatApi {

    String PATH_CREATE_SESSION = "/api/v1/chat/sessions";
    /**
     * POST /api/v1/chat/sessions : Create a new session
     *
     * @param createSessionRequest  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Session created (status code 201)
     */
    @Operation(
        operationId = "createSession",
        summary = "Create a new session",
        tags = { "Chat" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Session created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ChatApi.PATH_CREATE_SESSION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<SessionResponse>> createSession(
        @Parameter(name = "CreateSessionRequest", description = "", required = true) @Valid @RequestBody Mono<CreateSessionRequest> createSessionRequest,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_DELETE_SESSION = "/api/v1/chat/sessions/{sessionId}";
    /**
     * DELETE /api/v1/chat/sessions/{sessionId} : Delete session
     *
     * @param sessionId  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Session deleted (status code 204)
     */
    @Operation(
        operationId = "deleteSession",
        summary = "Delete session",
        tags = { "Chat" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Session deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ChatApi.PATH_DELETE_SESSION
    )
    Mono<ResponseEntity<Void>> deleteSession(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") String sessionId,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_SESSION_HISTORY = "/api/v1/chat/sessions/{sessionId}/history";
    /**
     * GET /api/v1/chat/sessions/{sessionId}/history : Get session conversation history
     *
     * @param sessionId  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Conversation history (status code 200)
     */
    @Operation(
        operationId = "getSessionHistory",
        summary = "Get session conversation history",
        tags = { "Chat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Conversation history", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionHistoryResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ChatApi.PATH_GET_SESSION_HISTORY,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<SessionHistoryResponse>> getSessionHistory(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") String sessionId,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_SESSIONS = "/api/v1/chat/sessions";
    /**
     * GET /api/v1/chat/sessions : List sessions
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @return Session list (status code 200)
     */
    @Operation(
        operationId = "listSessions",
        summary = "List sessions",
        tags = { "Chat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Session list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionListResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ChatApi.PATH_LIST_SESSIONS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<SessionListResponse>> listSessions(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit,
        @Parameter(name = "offset", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false, defaultValue = "0") Integer offset,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_POST_CHAT_MESSAGE = "/api/v1/chat/message";
    /**
     * POST /api/v1/chat/message : Send a chat message (SSE stream)
     *
     * @param chatMessageRequest  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return SSE stream of chat events (status code 200)
     */
    @Operation(
        operationId = "postChatMessage",
        summary = "Send a chat message (SSE stream)",
        tags = { "Chat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "SSE stream of chat events", content = {
                @Content(mediaType = "text/event-stream", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ChatApi.PATH_POST_CHAT_MESSAGE,
        produces = { "text/event-stream" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<String>> postChatMessage(
        @Parameter(name = "ChatMessageRequest", description = "", required = true) @Valid @RequestBody Mono<ChatMessageRequest> chatMessageRequest,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_RESET_SESSION = "/api/v1/chat/sessions/{sessionId}/reset";
    /**
     * POST /api/v1/chat/sessions/{sessionId}/reset : Reset session (clear turns)
     *
     * @param sessionId  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Session reset (status code 204)
     */
    @Operation(
        operationId = "resetSession",
        summary = "Reset session (clear turns)",
        tags = { "Chat" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Session reset")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ChatApi.PATH_RESET_SESSION
    )
    Mono<ResponseEntity<Void>> resetSession(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") String sessionId,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPDATE_SESSION = "/api/v1/chat/sessions/{sessionId}";
    /**
     * PATCH /api/v1/chat/sessions/{sessionId} : Update session
     *
     * @param sessionId  (required)
     * @param updateSessionRequest  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Session updated (status code 200)
     */
    @Operation(
        operationId = "updateSession",
        summary = "Update session",
        tags = { "Chat" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Session updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = ChatApi.PATH_UPDATE_SESSION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<SessionResponse>> updateSession(
        @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") String sessionId,
        @Parameter(name = "UpdateSessionRequest", description = "", required = true) @Valid @RequestBody Mono<UpdateSessionRequest> updateSessionRequest,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
