/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.synaptiq.infrastructure.in.web.api;

import com.synaptiq.infrastructure.in.web.dto.HealthResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-05T21:15:25.464614100-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Health", description = "Health checks — liveness and readiness probes")
public interface HealthApi {

    String PATH_HEALTH_CHECK = "/api/v1/health";
    /**
     * GET /api/v1/health : Liveness probe
     *
     * @return Service is alive (status code 200)
     */
    @Operation(
        operationId = "healthCheck",
        summary = "Liveness probe",
        tags = { "Health" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Service is alive", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HealthResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = HealthApi.PATH_HEALTH_CHECK,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<HealthResponse>> healthCheck(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_READINESS_CHECK = "/api/v1/health/ready";
    /**
     * GET /api/v1/health/ready : Readiness probe
     *
     * @return Service is ready (status code 200)
     */
    @Operation(
        operationId = "readinessCheck",
        summary = "Readiness probe",
        tags = { "Health" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Service is ready", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HealthResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = HealthApi.PATH_READINESS_CHECK,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<HealthResponse>> readinessCheck(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
