/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.spectrayan.synaptiq.infrastructure.in.web.api;

import com.spectrayan.synaptiq.infrastructure.in.web.dto.BrandingResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ContrastCheckResponse;
import org.springframework.lang.Nullable;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.PersonalizationResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ProblemDetails;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ThemeListResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-18T21:07:32.055501800-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Branding", description = "Branding — theming, personalization, visual identity")
public interface BrandingApi {

    String PATH_CHECK_CONTRAST = "/api/v1/config/contrast";
    /**
     * GET /api/v1/config/contrast : Check color contrast ratio
     *
     * @param fg  (required)
     * @param bg  (required)
     * @return Contrast result (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "checkContrast",
        summary = "Check color contrast ratio",
        tags = { "Branding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Contrast result", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ContrastCheckResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ContrastCheckResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BrandingApi.PATH_CHECK_CONTRAST,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ContrastCheckResponse>> checkContrast(
        @NotNull @Parameter(name = "fg", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "fg", required = true) String fg,
        @NotNull @Parameter(name = "bg", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "bg", required = true) String bg,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_BRANDING = "/api/v1/config/branding";
    /**
     * GET /api/v1/config/branding : Get branding config
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Branding config (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getBranding",
        summary = "Get branding config",
        tags = { "Branding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Branding config", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BrandingResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = BrandingResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BrandingApi.PATH_GET_BRANDING,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<BrandingResponse>> getBranding(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_PERSONALIZATION = "/api/v1/config/personalization";
    /**
     * GET /api/v1/config/personalization : Get personalization settings
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Personalization settings (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getPersonalization",
        summary = "Get personalization settings",
        tags = { "Branding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Personalization settings", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PersonalizationResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = PersonalizationResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BrandingApi.PATH_GET_PERSONALIZATION,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<PersonalizationResponse>> getPersonalization(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_PUBLIC_BRANDING = "/api/v1/config/branding/public";
    /**
     * GET /api/v1/config/branding/public : Get Public Branding
     * Retrieve public branding information for a tenant without authentication.
     *
     * @param xTenantID  (required)
     * @return Public branding configuration. (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Tenant not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getPublicBranding",
        summary = "Get Public Branding",
        description = "Retrieve public branding information for a tenant without authentication.",
        tags = { "Branding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Public branding configuration.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BrandingResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = BrandingResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "404", description = "Tenant not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BrandingApi.PATH_GET_PUBLIC_BRANDING,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<BrandingResponse>> getPublicBranding(
        @NotNull @Parameter(name = "X-Tenant-ID", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = true) String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_THEMES = "/api/v1/config/themes";
    /**
     * GET /api/v1/config/themes : Get theme presets
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Theme presets (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getThemes",
        summary = "Get theme presets",
        tags = { "Branding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Theme presets", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ThemeListResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ThemeListResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = BrandingApi.PATH_GET_THEMES,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ThemeListResponse>> getThemes(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPDATE_BRANDING = "/api/v1/config/branding";
    /**
     * PATCH /api/v1/config/branding : Update branding
     *
     * @param brandingResponse  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Branding updated (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateBranding",
        summary = "Update branding",
        tags = { "Branding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Branding updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BrandingResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = BrandingResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = BrandingApi.PATH_UPDATE_BRANDING,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<BrandingResponse>> updateBranding(
        @Parameter(name = "BrandingResponse", description = "", required = true) @Valid @RequestBody Mono<BrandingResponse> brandingResponse,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPDATE_PERSONALIZATION = "/api/v1/config/personalization";
    /**
     * PATCH /api/v1/config/personalization : Update personalization
     *
     * @param personalizationResponse  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Updated (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updatePersonalization",
        summary = "Update personalization",
        tags = { "Branding" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PersonalizationResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = PersonalizationResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = BrandingApi.PATH_UPDATE_PERSONALIZATION,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<PersonalizationResponse>> updatePersonalization(
        @Parameter(name = "PersonalizationResponse", description = "", required = true) @Valid @RequestBody Mono<PersonalizationResponse> personalizationResponse,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
