/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.spectrayan.synaptiq.infrastructure.in.web.api;

import com.spectrayan.synaptiq.infrastructure.in.web.dto.CreateCategoryRequest;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.DocumentListResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.KnowledgeBaseStatusResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.KnowledgeCategoryResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.KnowledgeDocumentResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.KnowledgeSearchRequest;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.KnowledgeSearchResponse;
import org.springframework.lang.Nullable;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ProblemDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-18T21:07:32.055501800-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "KnowledgeBase", description = "RAG & Knowledge Base — categorize, ingest, and search documents")
public interface KnowledgeBaseApi {

    String PATH_CREATE_KNOWLEDGE_CATEGORY = "/api/v1/kb/categories";
    /**
     * POST /api/v1/kb/categories : Create a new knowledge category
     *
     * @param createCategoryRequest  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Category created successfully (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "createKnowledgeCategory",
        summary = "Create a new knowledge category",
        tags = { "KnowledgeBase" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Category created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = KnowledgeCategoryResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = KnowledgeCategoryResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = KnowledgeBaseApi.PATH_CREATE_KNOWLEDGE_CATEGORY,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<KnowledgeCategoryResponse>> createKnowledgeCategory(
        @Parameter(name = "CreateCategoryRequest", description = "", required = true) @Valid @RequestBody Mono<CreateCategoryRequest> createCategoryRequest,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_DELETE_KNOWLEDGE_DOCUMENT = "/api/v1/kb/documents/{docId}";
    /**
     * DELETE /api/v1/kb/documents/{docId} : Delete a knowledge document
     *
     * @param docId  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Document deleted (status code 204)
     */
    @Operation(
        operationId = "deleteKnowledgeDocument",
        summary = "Delete a knowledge document",
        tags = { "KnowledgeBase" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Document deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = KnowledgeBaseApi.PATH_DELETE_KNOWLEDGE_DOCUMENT
    )
    Mono<ResponseEntity<Void>> deleteKnowledgeDocument(
        @Parameter(name = "docId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("docId") String docId,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_KNOWLEDGE_BASE_STATUS = "/api/v1/kb/status";
    /**
     * GET /api/v1/kb/status : Get knowledge base status and stats
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Status info (status code 200)
     */
    @Operation(
        operationId = "getKnowledgeBaseStatus",
        summary = "Get knowledge base status and stats",
        tags = { "KnowledgeBase" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Status info", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = KnowledgeBaseStatusResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KnowledgeBaseApi.PATH_GET_KNOWLEDGE_BASE_STATUS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<KnowledgeBaseStatusResponse>> getKnowledgeBaseStatus(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_KNOWLEDGE_DOCUMENT = "/api/v1/kb/documents/{docId}";
    /**
     * GET /api/v1/kb/documents/{docId} : Get knowledge document details
     *
     * @param docId  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Document details (status code 200)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getKnowledgeDocument",
        summary = "Get knowledge document details",
        tags = { "KnowledgeBase" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Document details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = KnowledgeDocumentResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = KnowledgeDocumentResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KnowledgeBaseApi.PATH_GET_KNOWLEDGE_DOCUMENT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<KnowledgeDocumentResponse>> getKnowledgeDocument(
        @Parameter(name = "docId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("docId") String docId,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_KNOWLEDGE_DOCUMENTS = "/api/v1/kb/documents";
    /**
     * GET /api/v1/kb/documents : List all knowledge documents
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @param categoryId  (optional)
     * @param tags  (optional)
     * @return List of documents (status code 200)
     */
    @Operation(
        operationId = "listKnowledgeDocuments",
        summary = "List all knowledge documents",
        tags = { "KnowledgeBase" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of documents", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DocumentListResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KnowledgeBaseApi.PATH_LIST_KNOWLEDGE_DOCUMENTS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<DocumentListResponse>> listKnowledgeDocuments(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(name = "categoryId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "categoryId", required = false) @Nullable String categoryId,
        @Parameter(name = "tags", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tags", required = false) @Nullable List<String> tags,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_SEARCH_KNOWLEDGE_BASE = "/api/v1/kb/search";
    /**
     * POST /api/v1/kb/search : Perform a similarity search on the knowledge base
     *
     * @param knowledgeSearchRequest  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Search results (status code 200)
     */
    @Operation(
        operationId = "searchKnowledgeBase",
        summary = "Perform a similarity search on the knowledge base",
        tags = { "KnowledgeBase" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Search results", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = KnowledgeSearchResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = KnowledgeBaseApi.PATH_SEARCH_KNOWLEDGE_BASE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<KnowledgeSearchResponse>> searchKnowledgeBase(
        @Parameter(name = "KnowledgeSearchRequest", description = "", required = true) @Valid @RequestBody Mono<KnowledgeSearchRequest> knowledgeSearchRequest,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPLOAD_KNOWLEDGE_DOCUMENT = "/api/v1/kb/documents";
    /**
     * POST /api/v1/kb/documents : Upload a new knowledge document
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @param tags  (optional)
     * @param file  (optional)
     * @param categoryId  (optional)
     * @return Document uploaded and ingestion started (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "uploadKnowledgeDocument",
        summary = "Upload a new knowledge document",
        tags = { "KnowledgeBase" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Document uploaded and ingestion started", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = KnowledgeDocumentResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = KnowledgeDocumentResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = KnowledgeBaseApi.PATH_UPLOAD_KNOWLEDGE_DOCUMENT,
        produces = { "application/json", "application/problem+json" },
        consumes = { "multipart/form-data" }
    )
    Mono<ResponseEntity<KnowledgeDocumentResponse>> uploadKnowledgeDocument(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(name = "tags", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tags", required = false) @Nullable List<String> tags,
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) Part file,
        @Parameter(name = "categoryId", description = "") @Valid @RequestPart(value = "categoryId", required = false) String categoryId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
