/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.spectrayan.synaptiq.infrastructure.in.web.api;

import org.springframework.format.annotation.DateTimeFormat;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.NotificationCountResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.NotificationListResponse;
import org.springframework.lang.Nullable;
import java.time.OffsetDateTime;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ProblemDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-10T17:15:52.297398600-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Notifications", description = "Notifications — in-app notifications, bell badge, mark-as-read")
public interface NotificationsApi {

    String PATH_CLEAR_ALL_NOTIFICATIONS = "/api/v1/notifications";
    /**
     * DELETE /api/v1/notifications : Clear all notifications
     * Deletes all notifications for the authenticated user in the specified tenant. 
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return All notifications cleared (status code 204)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "clearAllNotifications",
        summary = "Clear all notifications",
        description = "Deletes all notifications for the authenticated user in the specified tenant. ",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "204", description = "All notifications cleared"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = NotificationsApi.PATH_CLEAR_ALL_NOTIFICATIONS,
        produces = { "application/problem+json" }
    )
    Mono<ResponseEntity<Void>> clearAllNotifications(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_DISMISS_NOTIFICATION = "/api/v1/notifications/{id}";
    /**
     * DELETE /api/v1/notifications/{id} : Dismiss a notification
     * Permanently deletes a single notification for the authenticated user.
     *
     * @param id Notification ID (required)
     * @return Notification dismissed (status code 204)
     *         or Unauthorized (status code 401)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "dismissNotification",
        summary = "Dismiss a notification",
        description = "Permanently deletes a single notification for the authenticated user.",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notification dismissed"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = NotificationsApi.PATH_DISMISS_NOTIFICATION,
        produces = { "application/problem+json" }
    )
    Mono<ResponseEntity<Void>> dismissNotification(
        @Parameter(name = "id", description = "Notification ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_UNREAD_NOTIFICATION_COUNT = "/api/v1/notifications/unread-count";
    /**
     * GET /api/v1/notifications/unread-count : Get unread notification count
     * Returns the number of unread notifications for the bell badge.
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Unread count (status code 200)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "getUnreadNotificationCount",
        summary = "Get unread notification count",
        description = "Returns the number of unread notifications for the bell badge.",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Unread count", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotificationCountResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = NotificationCountResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NotificationsApi.PATH_GET_UNREAD_NOTIFICATION_COUNT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<NotificationCountResponse>> getUnreadNotificationCount(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_NOTIFICATIONS = "/api/v1/notifications";
    /**
     * GET /api/v1/notifications : List notifications
     * Cursor-based notification list for the authenticated user. Returns notifications for the specified tenant, ordered by creation time descending. 
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @param unreadOnly If true, only return unread notifications (optional, default to false)
     * @param before ISO 8601 cursor — only return notifications created before this timestamp (optional)
     * @param limit Maximum number of notifications to return (capped at 50) (optional, default to 20)
     * @return Paginated notification list (status code 200)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "listNotifications",
        summary = "List notifications",
        description = "Cursor-based notification list for the authenticated user. Returns notifications for the specified tenant, ordered by creation time descending. ",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Paginated notification list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotificationListResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = NotificationListResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NotificationsApi.PATH_LIST_NOTIFICATIONS,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<NotificationListResponse>> listNotifications(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(name = "unreadOnly", description = "If true, only return unread notifications", in = ParameterIn.QUERY) @Valid @RequestParam(value = "unreadOnly", required = false, defaultValue = "false") Boolean unreadOnly,
        @Parameter(name = "before", description = "ISO 8601 cursor — only return notifications created before this timestamp", in = ParameterIn.QUERY) @Valid @RequestParam(value = "before", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime before,
        @Parameter(name = "limit", description = "Maximum number of notifications to return (capped at 50)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_MARK_ALL_NOTIFICATIONS_READ = "/api/v1/notifications/read-all";
    /**
     * POST /api/v1/notifications/read-all : Mark all notifications as read
     * Marks all unread notifications as read for the authenticated user in the specified tenant. 
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return All notifications marked as read (status code 204)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "markAllNotificationsRead",
        summary = "Mark all notifications as read",
        description = "Marks all unread notifications as read for the authenticated user in the specified tenant. ",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "204", description = "All notifications marked as read"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NotificationsApi.PATH_MARK_ALL_NOTIFICATIONS_READ,
        produces = { "application/problem+json" }
    )
    Mono<ResponseEntity<Void>> markAllNotificationsRead(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_MARK_NOTIFICATION_AS_READ = "/api/v1/notifications/{id}";
    /**
     * PATCH /api/v1/notifications/{id} : Mark a notification as read
     * Marks a single notification as read for the authenticated user.
     *
     * @param id Notification ID (required)
     * @return Notification marked as read (status code 204)
     *         or Unauthorized (status code 401)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "markNotificationAsRead",
        summary = "Mark a notification as read",
        description = "Marks a single notification as read for the authenticated user.",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Notification marked as read"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = NotificationsApi.PATH_MARK_NOTIFICATION_AS_READ,
        produces = { "application/problem+json" }
    )
    Mono<ResponseEntity<Void>> markNotificationAsRead(
        @Parameter(name = "id", description = "Notification ID", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
