/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.spectrayan.synaptiq.infrastructure.in.web.api;

import com.spectrayan.synaptiq.infrastructure.in.web.dto.CreateRoleRequest;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ListRoles200Response;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ListScopes200Response;
import org.springframework.lang.Nullable;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.ProblemDetails;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.RoleResponse;
import com.spectrayan.synaptiq.infrastructure.in.web.dto.UpdateCustomRoleRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-18T21:07:32.055501800-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Roles", description = "Role management — RBAC roles and scopes")
public interface RolesApi {

    String PATH_CREATE_ROLE = "/api/v1/roles";
    /**
     * POST /api/v1/roles : Create a custom role
     *
     * @param createRoleRequest  (required)
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Role created (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createRole",
        summary = "Create a custom role",
        tags = { "Roles" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Role created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RoleResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RoleResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RolesApi.PATH_CREATE_ROLE,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<RoleResponse>> createRole(
        @Parameter(name = "CreateRoleRequest", description = "", required = true) @Valid @RequestBody Mono<CreateRoleRequest> createRoleRequest,
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_DELETE_ROLE = "/api/v1/roles/{roleSlug}";
    /**
     * DELETE /api/v1/roles/{roleSlug} : Delete a custom role
     *
     * @param roleSlug  (required)
     * @return Role deleted (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteRole",
        summary = "Delete a custom role",
        tags = { "Roles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Role deleted"),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = RolesApi.PATH_DELETE_ROLE,
        produces = { "application/problem+json" }
    )
    Mono<ResponseEntity<Void>> deleteRole(
        @Parameter(name = "roleSlug", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roleSlug") String roleSlug,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_ROLE = "/api/v1/roles/{roleSlug}";
    /**
     * GET /api/v1/roles/{roleSlug} : Get a role by slug
     *
     * @param roleSlug  (required)
     * @return Role details (status code 200)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getRole",
        summary = "Get a role by slug",
        tags = { "Roles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Role details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RoleResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RoleResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RolesApi.PATH_GET_ROLE,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<RoleResponse>> getRole(
        @Parameter(name = "roleSlug", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roleSlug") String roleSlug,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_ROLES = "/api/v1/roles";
    /**
     * GET /api/v1/roles : List available roles for a tenant
     *
     * @param xTenantID The tenant identifier for multi-tenant isolation (optional)
     * @return Role list (status code 200)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listRoles",
        summary = "List available roles for a tenant",
        tags = { "Roles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Role list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListRoles200Response.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ListRoles200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RolesApi.PATH_LIST_ROLES,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ListRoles200Response>> listRoles(
        @Size(min = 1, max = 100) @Parameter(name = "X-Tenant-ID", description = "The tenant identifier for multi-tenant isolation", in = ParameterIn.HEADER) @RequestHeader(value = "X-Tenant-ID", required = false) @Nullable String xTenantID,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_SCOPES = "/api/v1/scopes";
    /**
     * GET /api/v1/scopes : List all available scopes
     *
     * @return Scope list (status code 200)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listScopes",
        summary = "List all available scopes",
        tags = { "Roles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Scope list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ListScopes200Response.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ListScopes200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RolesApi.PATH_LIST_SCOPES,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ListScopes200Response>> listScopes(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPDATE_ROLE = "/api/v1/roles/{roleSlug}";
    /**
     * PUT /api/v1/roles/{roleSlug} : Update a custom role
     *
     * @param roleSlug  (required)
     * @param updateCustomRoleRequest  (required)
     * @return Role updated (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateRole",
        summary = "Update a custom role",
        tags = { "Roles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Role updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RoleResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = RoleResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = RolesApi.PATH_UPDATE_ROLE,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<RoleResponse>> updateRole(
        @Parameter(name = "roleSlug", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roleSlug") String roleSlug,
        @Parameter(name = "UpdateCustomRoleRequest", description = "", required = true) @Valid @RequestBody Mono<UpdateCustomRoleRequest> updateCustomRoleRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
