/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Outcome of an action execution
 */
export const ActionOutcome = {
    Success: 'SUCCESS',
    Failure: 'FAILURE',
    Pending: 'PENDING',
    Skipped: 'SKIPPED'
} as const;
export type ActionOutcome = typeof ActionOutcome[keyof typeof ActionOutcome];

