/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Admin role within a tenant
 */
export const AdminRole = {
    Owner: 'OWNER',
    Editor: 'EDITOR',
    Viewer: 'VIEWER'
} as const;
export type AdminRole = typeof AdminRole[keyof typeof AdminRole];

