/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LLMSpec } from './llm-spec.model';
import { ToolSpec } from './tool-spec.model';


/**
 * Agent node configuration within a workflow
 */
export interface AgentSpec { 
    id: string;
    name: string;
    systemPrompt?: string;
    description?: string;
    instructions?: string;
    llm?: LLMSpec;
    tools?: Array<ToolSpec>;
}

