/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AiPersonaResponse { 
    displayName?: string;
    tone?: string;
    customInstruction?: string;
    welcomeMessage?: string;
    starterPrompts?: Array<string>;
}

