/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BrandingResponse { 
    logoUrl?: string;
    primaryColor?: string;
    secondaryColor?: string;
    backgroundStyle?: string;
    headingFont?: string;
    bodyFont?: string;
    faviconUrl?: string;
    pageTitle?: string;
    showPlatformBranding?: boolean;
}

