/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogItemResponse } from './catalog-item-response.model';


export interface CatalogItemListResponse { 
    items?: Array<CatalogItemResponse>;
    total?: number;
}

