/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogItemStatus } from './catalog-item-status.model';


export interface CatalogItemResponse { 
    id?: string;
    tenantId?: string;
    status?: CatalogItemStatus;
    data?: { [key: string]: any; };
    createdAt?: string;
    updatedAt?: string;
}
export namespace CatalogItemResponse {
}


