/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatMessageRequest { 
    /**
     * The session to post the message to
     */
    sessionId: string;
    /**
     * The user\'s message (capped at 32K chars to prevent LLM cost spikes)
     */
    message: string;
    /**
     * Optional model override (e.g. gemini-2.5-flash)
     */
    modelOverride?: string;
}

