/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComponentsToggleResponse { 
    itemCard?: boolean;
    itemGrid?: boolean;
    itemDetail?: boolean;
    comparisonTable?: boolean;
    filterSummary?: boolean;
    resultCount?: boolean;
    emptyState?: boolean;
    actionConfirm?: boolean;
    infoBanner?: boolean;
}

