/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConnectionConfigResponseMcpServer { 
    serverUrl?: string;
    transport?: ConnectionConfigResponseMcpServer.TransportEnum;
    env?: { [key: string]: string; };
    enabledTools?: Array<string>;
}
export namespace ConnectionConfigResponseMcpServer {
    export const TransportEnum = {
        Stdio: 'STDIO',
        Http: 'HTTP',
        Ws: 'WS'
    } as const;
    export type TransportEnum = typeof TransportEnum[keyof typeof TransportEnum];
}


