/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Result of a connection test
 */
export interface ConnectionTestResponse { 
    success?: boolean;
    message?: string;
    durationMs?: number;
    testedAt?: string;
}

