/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialRefResponse } from './credential-ref-response.model';
import { DataSourceType } from './data-source-type.model';
import { ConnectionConfigResponse } from './connection-config-response.model';


/**
 * Create a new data source
 */
export interface CreateDataSourceRequest { 
    name: string;
    description?: string;
    type: DataSourceType;
    connection?: ConnectionConfigResponse;
    credentialRef?: CredentialRefResponse;
}
export namespace CreateDataSourceRequest {
}


