/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnectorType } from './connector-type.model';


/**
 * Request to create a new integration
 */
export interface CreateIntegrationRequest { 
    name: string;
    description?: string;
    connectorType: ConnectorType;
    /**
     * Built-in template ID to instantiate (e.g., \"rest-api-poll\", \"slack-notify\")
     */
    templateId?: string;
    /**
     * Key-value parameters for the template or adapter
     */
    parameters?: { [key: string]: string; };
    /**
     * Reference to credential/secret for authentication
     */
    credentialRef?: string;
}
export namespace CreateIntegrationRequest {
}


