/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessMode } from './access-mode.model';


export interface CreateTenantRequest { 
    tenantId: string;
    name: string;
    slug: string;
    displayLabel?: string;
    accessMode?: AccessMode;
}
export namespace CreateTenantRequest {
}


