/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogItemStatus } from './catalog-item-status.model';


export interface CreateCatalogItemRequest { 
    data: { [key: string]: any; };
    status?: CatalogItemStatus;
}
export namespace CreateCatalogItemRequest {
}


