/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialType } from './credential-type.model';


/**
 * Credential reference for data source authentication
 */
export interface CredentialRefResponse { 
    type?: CredentialType;
    /**
     * Secret identifier (GCP secret name, Vault path, or MongoDB doc ID)
     */
    secretRef?: string;
    /**
     * OAuth2 provider name (only for OAUTH2 type)
     */
    oauthProvider?: string;
}
export namespace CredentialRefResponse {
}


