/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DataSourceStatus = {
    Pending: 'PENDING',
    Connected: 'CONNECTED',
    Error: 'ERROR',
    Disabled: 'DISABLED'
} as const;
export type DataSourceStatus = typeof DataSourceStatus[keyof typeof DataSourceStatus];

