/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const DataSourceType = {
    SynaptiqNative: 'SYNAPTIQ_NATIVE',
    McpServer: 'MCP_SERVER',
    RestApi: 'REST_API',
    DatabaseDirect: 'DATABASE_DIRECT',
    FileUpload: 'FILE_UPLOAD'
} as const;
export type DataSourceType = typeof DataSourceType[keyof typeof DataSourceType];

