/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataSourceSchemaResponseFieldsInner } from './data-source-schema-response-fields-inner.model';


/**
 * Data source schema definition (inferred or manually defined)
 */
export interface DataSourceSchemaResponse { 
    schemaName?: string;
    fields?: Array<DataSourceSchemaResponseFieldsInner>;
    schemaVersion?: number;
    autoInferred?: boolean;
}

