/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Edge connecting two agent nodes
 */
export interface EdgeSpec { 
    source: string;
    target: string;
    condition?: EdgeSpec.ConditionEnum;
    label?: string;
}
export namespace EdgeSpec {
    export const ConditionEnum = {
        Always: 'ALWAYS',
        OnToolCalls: 'ON_TOOL_CALLS',
        Never: 'NEVER'
    } as const;
    export type ConditionEnum = typeof ConditionEnum[keyof typeof ConditionEnum];
}


