/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowSettingsSpec } from './flow-settings-spec.model';


/**
 * Request body for executing a workflow
 */
export interface ExecuteWorkflowRequest { 
    spec: FlowSettingsSpec;
    /**
     * Primary text input for the workflow
     */
    inputText?: string;
    /**
     * If true, validate the workflow without executing
     */
    dryRun?: boolean;
    /**
     * Optional node ID to start execution from (for partial runs)
     */
    startNodeId?: string;
    /**
     * Prior conversation context for the execution
     */
    priorContext?: string;
    /**
     * Key-value map of input variables for parameterized execution
     */
    inputVariables?: { [key: string]: any; };
}

