/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConnectorType } from './connector-type.model';
import { RouteStatus } from './route-status.model';


/**
 * Integration route configuration
 */
export interface IntegrationResponse { 
    routeConfigId?: string;
    tenantId?: string;
    name?: string;
    description?: string;
    connectorType?: ConnectorType;
    templateId?: string;
    parameters?: { [key: string]: string; };
    status?: RouteStatus;
    credentialRef?: string;
    camelRouteId?: string;
    lastTestedAt?: string;
    lastExecutedAt?: string;
    lastError?: string;
    createdAt?: string;
    updatedAt?: string;
}
export namespace IntegrationResponse {
}


