/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KnowledgeCategoryResponse { 
    /**
     * Unique identifier for the category
     */
    id: string;
    /**
     * Name of the category (e.g. HR, Engineering)
     */
    name: string;
    /**
     * Optional description of the category
     */
    description?: string;
}

