/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KnowledgeSearchRequest { 
    /**
     * The search query string
     */
    query: string;
    /**
     * Optional category to narrow down search
     */
    categoryId?: string;
    /**
     * Optional tags to filter by
     */
    tags?: Array<string>;
    topK?: number;
}

