/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationResponse } from './application-response.model';


export interface ListApplications200Response { 
    applications?: Array<ApplicationResponse>;
}

