/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeResponse } from './scope-response.model';


export interface ListScopes200Response { 
    scopes?: Array<ScopeResponse>;
}

