/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * MCP server connection configuration
 */
export interface MCPServerSpec { 
    id?: string;
    transport?: MCPServerSpec.TransportEnum;
    command?: string;
    args?: Array<string>;
    env?: { [key: string]: string; };
    url?: string;
}
export namespace MCPServerSpec {
    export const TransportEnum = {
        Stdio: 'STDIO',
        Http: 'HTTP',
        Ws: 'WS'
    } as const;
    export type TransportEnum = typeof TransportEnum[keyof typeof TransportEnum];
}


