/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Subscription plan tier
 */
export const PlanTier = {
    Free: 'FREE',
    Growth: 'GROWTH',
    Enterprise: 'ENTERPRISE'
} as const;
export type PlanTier = typeof PlanTier[keyof typeof PlanTier];

