/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RFC 9457 Problem Details for HTTP APIs
 */
export interface ProblemDetails { 
    /**
     * URI reference identifying the problem type
     */
    type?: string;
    /**
     * Short human-readable summary
     */
    title?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * Human-readable explanation
     */
    detail?: string;
    /**
     * URI reference identifying the specific occurrence
     */
    instance?: string;
}

