/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for AI-powered prompt regeneration
 */
export interface RegeneratePromptRequest { 
    nodeId: string;
    nodeLabel?: string;
    nodeDescription?: string;
    currentPrompt?: string;
    /**
     * User instruction for how the prompt should be regenerated
     */
    instruction?: string;
}

