/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Resource limits for workflow execution
 */
export interface ResourceLimitsSpec { 
    totalTimeoutMs?: number;
    stepTimeoutMs?: number;
    maxTokens?: number;
    rateLimitRps?: number;
}

