/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lifecycle status of an integration route
 */
export const RouteStatus = {
    Pending: 'PENDING',
    Active: 'ACTIVE',
    Error: 'ERROR',
    Disabled: 'DISABLED'
} as const;
export type RouteStatus = typeof RouteStatus[keyof typeof RouteStatus];

