/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemSnapshotResponse } from './item-snapshot-response.model';


export interface SavedItemResponse { 
    id?: string;
    itemId?: string;
    sessionId?: string;
    itemSnapshot?: ItemSnapshotResponse;
    createdAt?: string;
}

