/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SavedItemResponse } from './saved-item-response.model';


export interface SavedItemListResponse { 
    items?: Array<SavedItemResponse>;
    total?: number;
}

