/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScopeResponse { 
    /**
     * Scope identifier, e.g. workflow:create
     */
    slug: string;
    /**
     * Human-readable scope name
     */
    displayName: string;
    /**
     * Scope description
     */
    description?: string;
    /**
     * Resource category, e.g. workflow
     */
    resource: string;
    /**
     * Action within the resource, e.g. create
     */
    action: string;
}

