/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminRole } from './admin-role.model';


export interface TenantAdminResponse { 
    uid?: string;
    email?: string;
    role?: AdminRole;
    invitedAt?: string;
    accepted?: boolean;
}
export namespace TenantAdminResponse {
}


