/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tenant lifecycle status
 */
export const TenantStatus = {
    Active: 'ACTIVE',
    Suspended: 'SUSPENDED',
    Trial: 'TRIAL',
    Onboarding: 'ONBOARDING'
} as const;
export type TenantStatus = typeof TenantStatus[keyof typeof TenantStatus];

