/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThemePresetResponse } from './theme-preset-response.model';


export interface ThemeListResponse { 
    themes?: Array<ThemePresetResponse>;
}

