/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tool configuration for an agent
 */
export interface ToolSpec { 
    id?: string;
    type?: ToolSpec.TypeEnum;
    name?: string;
    importPath?: string;
    mcpServer?: string;
    mcpTool?: string;
    params?: { [key: string]: any; };
}
export namespace ToolSpec {
    export const TypeEnum = {
        Python: 'PYTHON',
        Java: 'JAVA',
        Mcp: 'MCP',
        Langchain: 'LANGCHAIN',
        SpringBean: 'SPRING_BEAN'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


