/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToolDefinitionResponse } from './tool-definition-response.model';


/**
 * List of available tools grouped by category
 */
export interface ToolCatalogResponse { 
    tools?: Array<ToolDefinitionResponse>;
}

