/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanTier } from './plan-tier.model';
import { AccessMode } from './access-mode.model';


/**
 * Partial update for tenant org-level fields. All fields are optional.
 */
export interface UpdateTenantRequest { 
    name?: string;
    slug?: string;
    catalogLabel?: string;
    accessMode?: AccessMode;
    planTier?: PlanTier;
    /**
     * MongoDB connection URI for tenant-isolated database
     */
    dbConnectionUri?: string;
}
export namespace UpdateTenantRequest {
}


