/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCustomRoleRequest { 
    /**
     * Updated display name
     */
    displayName?: string;
    /**
     * Updated description
     */
    description?: string;
    /**
     * Updated scope slugs this role grants
     */
    scopeSlugs?: Array<string>;
}

