/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserResponse { 
    uid?: string;
    email?: string;
    displayName?: string;
    role?: string;
    emailVerified?: boolean;
    tenantId?: string;
}

