/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NodeExecutionStatus } from './node-execution-status.model';


/**
 * Execution details for a single node within a workflow run
 */
export interface WorkflowRunNodeDetail { 
    status?: NodeExecutionStatus;
    /**
     * Execution duration in milliseconds
     */
    durationMs?: number;
    /**
     * Node output text
     */
    output?: string;
    /**
     * Error message if the node failed
     */
    error?: string;
    startedAt?: string;
    completedAt?: string;
}
export namespace WorkflowRunNodeDetail {
}


