/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlowSettingsSpec } from './flow-settings-spec.model';


export interface WorkflowResponse { 
    id?: string;
    tenantId?: string;
    spec?: FlowSettingsSpec;
    isPublic?: boolean;
    shareToken?: string;
    createdAt?: string;
}

