/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Input field definition for parameterized workflow execution
 */
export interface WorkflowInput { 
    name: string;
    label?: string;
    /**
     * Input type (text, number, select, boolean, etc.)
     */
    type: string;
    description?: string;
    required?: boolean;
    defaultValue?: any | null;
    /**
     * Available options for select-type inputs
     */
    options?: Array<string>;
}

