/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowRunNodeDetail } from './workflow-run-node-detail.model';


/**
 * Detailed result of a workflow execution run including per-node results
 */
export interface WorkflowRunDetail { 
    runId: string;
    workflowId: string;
    status: WorkflowRunDetail.StatusEnum;
    startedAt: string;
    completedAt?: string;
    /**
     * Currently executing node ID (when status is RUNNING)
     */
    currentNode?: string;
    totalDurationMs?: number;
    /**
     * Final output of the workflow execution
     */
    result?: string;
    /**
     * Per-node execution details keyed by node ID
     */
    nodes?: { [key: string]: WorkflowRunNodeDetail; };
}
export namespace WorkflowRunDetail {
    export const StatusEnum = {
        Running: 'RUNNING',
        Completed: 'COMPLETED',
        Error: 'ERROR',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


