/**
 * Synaptiq API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Summary of a workflow execution run
 */
export interface WorkflowRunSummary { 
    runId: string;
    workflowId: string;
    status: WorkflowRunSummary.StatusEnum;
    startedAt: string;
    completedAt?: string;
    /**
     * Duration of the most recent node execution
     */
    durationMs?: number;
    /**
     * Total duration of the entire run
     */
    totalDurationMs?: number;
}
export namespace WorkflowRunSummary {
    export const StatusEnum = {
        Running: 'RUNNING',
        Completed: 'COMPLETED',
        Error: 'ERROR',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


